FROM node:10-alpine

# Installs latest Chromium (71) package.
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge \
      nss@edge \
      freetype@edge \
      harfbuzz@edge \
      ttf-freefont@edge \
      dumb-init@edge

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Add user so we don't need --no-sandbox.
RUN mkdir -p /home/node/Downloads \
    && chown -R node:node /home/node

# Run everything after as non-privileged user.
USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app/export

COPY export/package.json export/yarn.lock ./

ENTRYPOINT ["dumb-init", "--"]
CMD yarn && yarn dev
