FROM node:22-alpine

# Installs Chromium package.
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium && \
    corepack enable

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Add user so we don't need --no-sandbox.
RUN mkdir -p /home/node/Downloads \
    && chown -R node:node /home/node

# Run everything after as non-privileged user.
USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

CMD pnpm install && (cd export && pnpm dev -- --exitcrash)
