// flow-typed signature: b4cb7b2f9aac2b95992ac1f51272b1d0
// flow-typed version: <<STUB>>/dom-to-image_v^2.5.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-to-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-to-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-to-image/dist/dom-to-image.min' {
  declare module.exports: any;
}

declare module 'dom-to-image/Gruntfile' {
  declare module.exports: any;
}

declare module 'dom-to-image/karma.conf' {
  declare module.exports: any;
}

declare module 'dom-to-image/spec/dom-to-image.spec' {
  declare module.exports: any;
}

declare module 'dom-to-image/src/dom-to-image' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom-to-image/dist/dom-to-image.min.js' {
  declare module.exports: $Exports<'dom-to-image/dist/dom-to-image.min'>;
}
declare module 'dom-to-image/Gruntfile.js' {
  declare module.exports: $Exports<'dom-to-image/Gruntfile'>;
}
declare module 'dom-to-image/karma.conf.js' {
  declare module.exports: $Exports<'dom-to-image/karma.conf'>;
}
declare module 'dom-to-image/spec/dom-to-image.spec.js' {
  declare module.exports: $Exports<'dom-to-image/spec/dom-to-image.spec'>;
}
declare module 'dom-to-image/src/dom-to-image.js' {
  declare module.exports: $Exports<'dom-to-image/src/dom-to-image'>;
}
