// flow-typed signature: 3fc2b0900736dd544fcbdf41ebfda4f4
// flow-typed version: <<STUB>>/happypack_v^2.2.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'happypack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'happypack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'happypack/lib/applyLoaders' {
  declare module.exports: any;
}

declare module 'happypack/lib/fnOnce' {
  declare module.exports: any;
}

declare module 'happypack/lib/fnOncePedantic' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyFakeCompiler' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyFakeLoaderContext' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyFSCache' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyLoader' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyMessage' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyPlugin' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyRPCHandler' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyTestUtils' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyThread' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyThreadPool' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyUtils' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyWorker' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyWorkerChannel' {
  declare module.exports: any;
}

declare module 'happypack/lib/JSONSerializer' {
  declare module.exports: any;
}

declare module 'happypack/lib/OptionParser' {
  declare module.exports: any;
}

declare module 'happypack/lib/serializeError' {
  declare module.exports: any;
}

declare module 'happypack/lib/SourceMapSerializer' {
  declare module.exports: any;
}

declare module 'happypack/lib/WebpackUtils' {
  declare module.exports: any;
}

declare module 'happypack/loader' {
  declare module.exports: any;
}

declare module 'happypack/scripts/loader-support-status/dist/main' {
  declare module.exports: any;
}

declare module 'happypack/scripts/loader-support-status/index' {
  declare module.exports: any;
}

declare module 'happypack/scripts/loader-support-status/lib/a' {
  declare module.exports: any;
}

declare module 'happypack/scripts/loader-support-status/lib/b' {
  declare module.exports: any;
}

declare module 'happypack/scripts/loader-support-status/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'happypack/lib/applyLoaders.js' {
  declare module.exports: $Exports<'happypack/lib/applyLoaders'>;
}
declare module 'happypack/lib/fnOnce.js' {
  declare module.exports: $Exports<'happypack/lib/fnOnce'>;
}
declare module 'happypack/lib/fnOncePedantic.js' {
  declare module.exports: $Exports<'happypack/lib/fnOncePedantic'>;
}
declare module 'happypack/lib/HappyFakeCompiler.js' {
  declare module.exports: $Exports<'happypack/lib/HappyFakeCompiler'>;
}
declare module 'happypack/lib/HappyFakeLoaderContext.js' {
  declare module.exports: $Exports<'happypack/lib/HappyFakeLoaderContext'>;
}
declare module 'happypack/lib/HappyFSCache.js' {
  declare module.exports: $Exports<'happypack/lib/HappyFSCache'>;
}
declare module 'happypack/lib/HappyLoader.js' {
  declare module.exports: $Exports<'happypack/lib/HappyLoader'>;
}
declare module 'happypack/lib/HappyMessage.js' {
  declare module.exports: $Exports<'happypack/lib/HappyMessage'>;
}
declare module 'happypack/lib/HappyPlugin.js' {
  declare module.exports: $Exports<'happypack/lib/HappyPlugin'>;
}
declare module 'happypack/lib/HappyRPCHandler.js' {
  declare module.exports: $Exports<'happypack/lib/HappyRPCHandler'>;
}
declare module 'happypack/lib/HappyTestUtils.js' {
  declare module.exports: $Exports<'happypack/lib/HappyTestUtils'>;
}
declare module 'happypack/lib/HappyThread.js' {
  declare module.exports: $Exports<'happypack/lib/HappyThread'>;
}
declare module 'happypack/lib/HappyThreadPool.js' {
  declare module.exports: $Exports<'happypack/lib/HappyThreadPool'>;
}
declare module 'happypack/lib/HappyUtils.js' {
  declare module.exports: $Exports<'happypack/lib/HappyUtils'>;
}
declare module 'happypack/lib/HappyWorker.js' {
  declare module.exports: $Exports<'happypack/lib/HappyWorker'>;
}
declare module 'happypack/lib/HappyWorkerChannel.js' {
  declare module.exports: $Exports<'happypack/lib/HappyWorkerChannel'>;
}
declare module 'happypack/lib/JSONSerializer.js' {
  declare module.exports: $Exports<'happypack/lib/JSONSerializer'>;
}
declare module 'happypack/lib/OptionParser.js' {
  declare module.exports: $Exports<'happypack/lib/OptionParser'>;
}
declare module 'happypack/lib/serializeError.js' {
  declare module.exports: $Exports<'happypack/lib/serializeError'>;
}
declare module 'happypack/lib/SourceMapSerializer.js' {
  declare module.exports: $Exports<'happypack/lib/SourceMapSerializer'>;
}
declare module 'happypack/lib/WebpackUtils.js' {
  declare module.exports: $Exports<'happypack/lib/WebpackUtils'>;
}
declare module 'happypack/loader.js' {
  declare module.exports: $Exports<'happypack/loader'>;
}
declare module 'happypack/scripts/loader-support-status/dist/main.js' {
  declare module.exports: $Exports<'happypack/scripts/loader-support-status/dist/main'>;
}
declare module 'happypack/scripts/loader-support-status/index.js' {
  declare module.exports: $Exports<'happypack/scripts/loader-support-status/index'>;
}
declare module 'happypack/scripts/loader-support-status/lib/a.js' {
  declare module.exports: $Exports<'happypack/scripts/loader-support-status/lib/a'>;
}
declare module 'happypack/scripts/loader-support-status/lib/b.js' {
  declare module.exports: $Exports<'happypack/scripts/loader-support-status/lib/b'>;
}
declare module 'happypack/scripts/loader-support-status/loader.js' {
  declare module.exports: $Exports<'happypack/scripts/loader-support-status/loader'>;
}
