// flow-typed signature: 5b6b997ef93cc79bfc10b0c584501fd5
// flow-typed version: <<STUB>>/js-search_v^1.3.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-search' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-search/dist/js-search' {
  declare module.exports: any;
}

declare module 'js-search/dist/js-search.min' {
  declare module.exports: any;
}

declare module 'js-search/flyfile' {
  declare module.exports: any;
}

declare module 'js-search/karma.conf' {
  declare module.exports: any;
}

declare module 'js-search/source/mocks/node-mock' {
  declare module.exports: any;
}

declare module 'js-search/source/node-export' {
  declare module.exports: any;
}

declare module 'js-search/tests/index-strategy/all-substrings-index-strategy' {
  declare module.exports: any;
}

declare module 'js-search/tests/index-strategy/exact-word-index-strategy' {
  declare module.exports: any;
}

declare module 'js-search/tests/index-strategy/prefix-index-strategy' {
  declare module.exports: any;
}

declare module 'js-search/tests/sanitizer/case-sensitive-sanitizer' {
  declare module.exports: any;
}

declare module 'js-search/tests/sanitizer/lower-case-sanitizer' {
  declare module.exports: any;
}

declare module 'js-search/tests/search-index/tf-idf-search-index' {
  declare module.exports: any;
}

declare module 'js-search/tests/search-index/unordered-search-index' {
  declare module.exports: any;
}

declare module 'js-search/tests/search' {
  declare module.exports: any;
}

declare module 'js-search/tests/token-highlighter' {
  declare module.exports: any;
}

declare module 'js-search/tests/tokenizer/simple-tokenizer' {
  declare module.exports: any;
}

declare module 'js-search/tests/tokenizer/stemming-tokenizer' {
  declare module.exports: any;
}

declare module 'js-search/tests/tokenizer/stop-words-tokenizer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-search/dist/js-search.js' {
  declare module.exports: $Exports<'js-search/dist/js-search'>;
}
declare module 'js-search/dist/js-search.min.js' {
  declare module.exports: $Exports<'js-search/dist/js-search.min'>;
}
declare module 'js-search/flyfile.js' {
  declare module.exports: $Exports<'js-search/flyfile'>;
}
declare module 'js-search/karma.conf.js' {
  declare module.exports: $Exports<'js-search/karma.conf'>;
}
declare module 'js-search/source/mocks/node-mock.js' {
  declare module.exports: $Exports<'js-search/source/mocks/node-mock'>;
}
declare module 'js-search/source/node-export.js' {
  declare module.exports: $Exports<'js-search/source/node-export'>;
}
declare module 'js-search/tests/index-strategy/all-substrings-index-strategy.js' {
  declare module.exports: $Exports<'js-search/tests/index-strategy/all-substrings-index-strategy'>;
}
declare module 'js-search/tests/index-strategy/exact-word-index-strategy.js' {
  declare module.exports: $Exports<'js-search/tests/index-strategy/exact-word-index-strategy'>;
}
declare module 'js-search/tests/index-strategy/prefix-index-strategy.js' {
  declare module.exports: $Exports<'js-search/tests/index-strategy/prefix-index-strategy'>;
}
declare module 'js-search/tests/sanitizer/case-sensitive-sanitizer.js' {
  declare module.exports: $Exports<'js-search/tests/sanitizer/case-sensitive-sanitizer'>;
}
declare module 'js-search/tests/sanitizer/lower-case-sanitizer.js' {
  declare module.exports: $Exports<'js-search/tests/sanitizer/lower-case-sanitizer'>;
}
declare module 'js-search/tests/search-index/tf-idf-search-index.js' {
  declare module.exports: $Exports<'js-search/tests/search-index/tf-idf-search-index'>;
}
declare module 'js-search/tests/search-index/unordered-search-index.js' {
  declare module.exports: $Exports<'js-search/tests/search-index/unordered-search-index'>;
}
declare module 'js-search/tests/search.js' {
  declare module.exports: $Exports<'js-search/tests/search'>;
}
declare module 'js-search/tests/token-highlighter.js' {
  declare module.exports: $Exports<'js-search/tests/token-highlighter'>;
}
declare module 'js-search/tests/tokenizer/simple-tokenizer.js' {
  declare module.exports: $Exports<'js-search/tests/tokenizer/simple-tokenizer'>;
}
declare module 'js-search/tests/tokenizer/stemming-tokenizer.js' {
  declare module.exports: $Exports<'js-search/tests/tokenizer/stemming-tokenizer'>;
}
declare module 'js-search/tests/tokenizer/stop-words-tokenizer.js' {
  declare module.exports: $Exports<'js-search/tests/tokenizer/stop-words-tokenizer'>;
}
