// flow-typed signature: 317a7468fe2ea3062fc85634ea2e32b3
// flow-typed version: <<STUB>>/nusmoderator_v^2.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nusmoderator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nusmoderator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nusmoderator/dist/nusmoderator' {
  declare module.exports: any;
}

declare module 'nusmoderator/dist/nusmoderator.min' {
  declare module.exports: any;
}

declare module 'nusmoderator/es/academicCalendar' {
  declare module.exports: any;
}

declare module 'nusmoderator/es/index' {
  declare module.exports: any;
}

declare module 'nusmoderator/lib/academicCalendar' {
  declare module.exports: any;
}

declare module 'nusmoderator/lib/index' {
  declare module.exports: any;
}

declare module 'nusmoderator/src/academicCalendar' {
  declare module.exports: any;
}

declare module 'nusmoderator/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nusmoderator/dist/nusmoderator.js' {
  declare module.exports: $Exports<'nusmoderator/dist/nusmoderator'>;
}
declare module 'nusmoderator/dist/nusmoderator.min.js' {
  declare module.exports: $Exports<'nusmoderator/dist/nusmoderator.min'>;
}
declare module 'nusmoderator/es/academicCalendar.js' {
  declare module.exports: $Exports<'nusmoderator/es/academicCalendar'>;
}
declare module 'nusmoderator/es/index.js' {
  declare module.exports: $Exports<'nusmoderator/es/index'>;
}
declare module 'nusmoderator/lib/academicCalendar.js' {
  declare module.exports: $Exports<'nusmoderator/lib/academicCalendar'>;
}
declare module 'nusmoderator/lib/index.js' {
  declare module.exports: $Exports<'nusmoderator/lib/index'>;
}
declare module 'nusmoderator/src/academicCalendar.js' {
  declare module.exports: $Exports<'nusmoderator/src/academicCalendar'>;
}
declare module 'nusmoderator/src/index.js' {
  declare module.exports: $Exports<'nusmoderator/src/index'>;
}
