// flow-typed signature: ad5075bce9ede2846f8e4f292ee5e3ca
// flow-typed version: <<STUB>>/optimize-css-assets-webpack-plugin_v^2.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optimize-css-assets-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'optimize-css-assets-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'optimize-css-assets-webpack-plugin/index' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin'>;
}
declare module 'optimize-css-assets-webpack-plugin/index.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin'>;
}
