// flow-typed signature: 6f0d6a76eebf2fc2a1692bb601c825ec
// flow-typed version: <<STUB>>/react-select-fast-filter-options_v0.0.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select-fast-filter-options'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select-fast-filter-options' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-select-fast-filter-options/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-select-fast-filter-options/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-select-fast-filter-options/dist/umd/react-select-fast-filter-options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-select-fast-filter-options/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-select-fast-filter-options/dist/commonjs/index'>;
}
declare module 'react-select-fast-filter-options/dist/es/index.js' {
  declare module.exports: $Exports<'react-select-fast-filter-options/dist/es/index'>;
}
declare module 'react-select-fast-filter-options/dist/umd/react-select-fast-filter-options.js' {
  declare module.exports: $Exports<'react-select-fast-filter-options/dist/umd/react-select-fast-filter-options'>;
}
