// flow-typed signature: d0ce18f6e9badf93344bdcbc04631ee4
// flow-typed version: <<STUB>>/react-disqus-thread_v^0.4.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-disqus-thread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-disqus-thread' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-disqus-thread/lib/components/__tests__/DisqusThread-test' {
  declare module.exports: any;
}

declare module 'react-disqus-thread/lib/components/DisqusThread' {
  declare module.exports: any;
}

declare module 'react-disqus-thread/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-disqus-thread/lib/components/__tests__/DisqusThread-test.js' {
  declare module.exports: $Exports<'react-disqus-thread/lib/components/__tests__/DisqusThread-test'>;
}
declare module 'react-disqus-thread/lib/components/DisqusThread.js' {
  declare module.exports: $Exports<'react-disqus-thread/lib/components/DisqusThread'>;
}
declare module 'react-disqus-thread/lib/main.js' {
  declare module.exports: $Exports<'react-disqus-thread/lib/main'>;
}
