// flow-typed signature: 37ee76ffdb905916b723637035c80831
// flow-typed version: <<STUB>>/react-autobind_v^1.0.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-autobind'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-autobind' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-autobind/lib/autoBind' {
  declare module.exports: any;
}

declare module 'react-autobind/src/autoBind' {
  declare module.exports: any;
}

declare module 'react-autobind/test/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-autobind/index' {
  declare module.exports: $Exports<'react-autobind'>;
}
declare module 'react-autobind/index.js' {
  declare module.exports: $Exports<'react-autobind'>;
}
declare module 'react-autobind/lib/autoBind.js' {
  declare module.exports: $Exports<'react-autobind/lib/autoBind'>;
}
declare module 'react-autobind/src/autoBind.js' {
  declare module.exports: $Exports<'react-autobind/src/autoBind'>;
}
declare module 'react-autobind/test/spec.js' {
  declare module.exports: $Exports<'react-autobind/test/spec'>;
}
