fixes:
  # For now we only report website coverage, and since tests are run directly in
  # the /website folder we need to add this
  - "::website/"
ignore:
  # Ignore webworkers since we can't test them
  - "**/*.worker.ts" 
  - "**/*.worker.js" 
