# Netlify configuration to deploy site

[build]
  base    = "website"
  publish = "website/dist"
  command = "npm rebuild node-sass && yarn build prod"
  environment = { NODE_VERSION = "lts/dubnium" }
