DROP TABLE IF EXISTS lesson CASCADE;
DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS venue CASCADE;
DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS term CASCADE;
DROP TABLE IF EXISTS school CASCADE;
