// flow-typed signature: efdc7c2c22939bf6cabd15d075d0b0c6
// flow-typed version: <<STUB>>/yargs_v12.0.5/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yargs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yargs' {
  declare type Argv = {
    _: string[],
    $0: string,

    [argName: string]: any,
  }

  declare type CommandModule = {|
    command: string | string[],
    aliases?: string | string[],
    describe: string | false,
    builder?: (any) => void | any,
    handler?: (Argv) => void,
  |}

  declare module.exports: any;
}
