// flow-typed signature: 1576d6a9de9f974f299ee7f840b5afe1
// flow-typed version: <<STUB>>/@sentry/node_v4.5.3/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/node/dist/backend' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/client' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/handlers' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/index' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/integrations/console' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/integrations/http' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/integrations/index' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/integrations/linkederrors' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/integrations/onuncaughtexception' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/integrations/onunhandledrejection' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/integrations/pluggable/modules' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/integrations/pluggable/transaction' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/parsers' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/sdk' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/transports/base' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/transports/http' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/transports/https' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/transports/index' {
  declare module.exports: any;
}

declare module '@sentry/node/dist/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/node/dist/backend.js' {
  declare module.exports: $Exports<'@sentry/node/dist/backend'>;
}
declare module '@sentry/node/dist/client.js' {
  declare module.exports: $Exports<'@sentry/node/dist/client'>;
}
declare module '@sentry/node/dist/handlers.js' {
  declare module.exports: $Exports<'@sentry/node/dist/handlers'>;
}
declare module '@sentry/node/dist/index.js' {
  declare module.exports: $Exports<'@sentry/node/dist/index'>;
}
declare module '@sentry/node/dist/integrations/console.js' {
  declare module.exports: $Exports<'@sentry/node/dist/integrations/console'>;
}
declare module '@sentry/node/dist/integrations/http.js' {
  declare module.exports: $Exports<'@sentry/node/dist/integrations/http'>;
}
declare module '@sentry/node/dist/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/node/dist/integrations/index'>;
}
declare module '@sentry/node/dist/integrations/linkederrors.js' {
  declare module.exports: $Exports<'@sentry/node/dist/integrations/linkederrors'>;
}
declare module '@sentry/node/dist/integrations/onuncaughtexception.js' {
  declare module.exports: $Exports<'@sentry/node/dist/integrations/onuncaughtexception'>;
}
declare module '@sentry/node/dist/integrations/onunhandledrejection.js' {
  declare module.exports: $Exports<'@sentry/node/dist/integrations/onunhandledrejection'>;
}
declare module '@sentry/node/dist/integrations/pluggable/modules.js' {
  declare module.exports: $Exports<'@sentry/node/dist/integrations/pluggable/modules'>;
}
declare module '@sentry/node/dist/integrations/pluggable/transaction.js' {
  declare module.exports: $Exports<'@sentry/node/dist/integrations/pluggable/transaction'>;
}
declare module '@sentry/node/dist/parsers.js' {
  declare module.exports: $Exports<'@sentry/node/dist/parsers'>;
}
declare module '@sentry/node/dist/sdk.js' {
  declare module.exports: $Exports<'@sentry/node/dist/sdk'>;
}
declare module '@sentry/node/dist/transports/base.js' {
  declare module.exports: $Exports<'@sentry/node/dist/transports/base'>;
}
declare module '@sentry/node/dist/transports/http.js' {
  declare module.exports: $Exports<'@sentry/node/dist/transports/http'>;
}
declare module '@sentry/node/dist/transports/https.js' {
  declare module.exports: $Exports<'@sentry/node/dist/transports/https'>;
}
declare module '@sentry/node/dist/transports/index.js' {
  declare module.exports: $Exports<'@sentry/node/dist/transports/index'>;
}
declare module '@sentry/node/dist/version.js' {
  declare module.exports: $Exports<'@sentry/node/dist/version'>;
}
