// Non-camelCase things generated by ANTLR.

import * as R from 'ramda';

import { NusModsLexer, NusModsVisitor } from './antlr4';
import {
  CohortCondition,
  CohortRule,
  PrereqTree,
  ProgramTypeCondition,
  ProgramTypeRule,
} from '../../types/modules';
import { Logger } from '../logger';
import {
  NusModsParser,
  BinopContext,
  CompoundContext,
  Course_itemsContext,
  CoursesContext,
  OpContext,
  OverallContext,
  PrereqContext,
  PrimitiveContext,
  ProgramsContext,
  Cohort_yearsContext,
  Cohort_conditionalContext,
  Subject_yearsContext,
  Subject_years_conditionalContext,
  Program_typesContext,
  Program_types_conditionalContext,
  Program_types_gateContext,
} from './antlr4/NusModsParser';
import { CharStreams, BufferedTokenStream, ParserRuleContext } from 'antlr4ts';
import { AbstractParseTreeVisitor } from 'antlr4ts/tree/AbstractParseTreeVisitor';

function generateAndBranch(modules: Array<PrereqTree>) {
  const children: Array<PrereqTree> = R.uniq(modules);
  // Simplifying the expression
  if (children.length === 1) {
    return children[0];
  }

  // Simplify conjunction
  // @ts-ignore -- TS doesn't recognise Object.hasOwnProperty is a type guard.
  const result = children.flatMap((child) => (Object.hasOwn(child, 'and') ? child.and : child));
  if (result.length === 1) {
    return result[0];
  }
  return { and: result };
}

function generateOrBranch(modules: Array<PrereqTree>) {
  const children: Array<PrereqTree> = R.uniq(modules);
  // Simplifying the expression:
  if (children.length === 1) {
    return children[0];
  }
  // Simplify disjunction
  // @ts-ignore -- TS doesn't recognise Object.hasOwnProperty is a type guard.
  const result = children.flatMap((child) => (Object.hasOwn(child, 'or') ? child.or : child));
  if (result.length === 1) {
    return result[0];
  }
  return { or: result };
}

// Flatten a program-type gate (which may be parenthesised and/or a disjunction
// of program types) down to its list of program types.
function collectGateProgramTypes(gate: Program_types_gateContext): Array<Program_typesContext> {
  const inner = gate.program_types_gate();
  return inner !== undefined ? collectGateProgramTypes(inner) : gate.program_types();
}

/**
 * ReqTreeVisitor, implements the visitor design pattern using
 * the auto generated visitor from ANTLR4.
 */
class ReqTreeVisitor
  extends AbstractParseTreeVisitor<PrereqTree>
  implements NusModsVisitor<PrereqTree>
{
  errors: Array<Error>;
  constructor() {
    super();
    this.errors = [];
  }

  protected defaultResult(): PrereqTree {
    return '';
  }

  visitWithSingularAlternative(ctx: ParserRuleContext, rule: string): PrereqTree {
    if (ctx.children === undefined) {
      return '';
    }
    // This can have either 0 children (ie all empty and filtered out)
    // Or 1 child (ie one subrule is populated)
    const result = ctx.children.map((child) => child.accept(this)).filter((n) => n !== '');
    if (result.length !== 0 && result.length !== 1) {
      this.errors.push(new Error(`${rule} has children != 0/1 which is impossible ${result}`));
      return '';
    }
    return result.length === 0 ? '' : (result[0] as PrereqTree);
  }

  // @ts-ignore
  visitOverall?: ((ctx: OverallContext) => PrereqTree) | undefined = (ctx) => {
    return ctx?.compound()?.accept(this);
  };

  visitCompound?: ((ctx: CompoundContext) => PrereqTree) | undefined = (ctx) => {
    return this.visitWithSingularAlternative(ctx, 'compound');
  };

  // @ts-ignore
  visitBinop?: ((ctx: BinopContext) => PrereqTree) | undefined = (ctx) => {
    const lhs = ctx?.op()?.accept(this);
    const rhs = ctx?.compound()?.accept(this);
    const boolOp = ctx?.boolean_expr()?.text;
    if (lhs === undefined || rhs === undefined) {
      this.errors.push(new Error(`visitBinop bad lhs/rhs: lhs:${lhs} rhs:${rhs}`));
      return;
    }
    // Simplifying the tree
    if (lhs === '' && rhs === '') {
      return '';
    } else if (lhs === '') {
      return rhs;
    } else if (rhs == '') {
      return lhs;
    }
    switch (boolOp) {
      case 'AND':
        return generateAndBranch([lhs, rhs]);
      case 'OR':
        return generateOrBranch([lhs, rhs]);
      default:
        this.errors.push(new Error(`visitBinop unkown Binop type: ${boolOp}`));
        return;
    }
  };

  visitOp?: ((ctx: OpContext) => PrereqTree) | undefined = (ctx) => {
    return this.visitWithSingularAlternative(ctx, 'op');
  };

  visitPrimitive?: ((ctx: PrimitiveContext) => PrereqTree) | undefined = (ctx) => {
    return this.visitWithSingularAlternative(ctx, 'primitive');
  };

  visitPrereq?: ((ctx: PrereqContext) => PrereqTree) | undefined = (ctx) => {
    return this.visitWithSingularAlternative(ctx, 'prereq');
  };

  visitCourses?: ((ctx: CoursesContext) => PrereqTree) | undefined = (ctx) => {
    const courses = ctx
      .course_items()
      .PROGRAMS_VALUE()
      .map((node) => node.text);
    const courseCount = ctx.contains_number();
    // Previously assumed: if there is no course count, then all courses are
    // required.
    // Update 26/06/2026: upstream prerequisite-rule semantics clarified that an
    // omitted course count is equivalent to (1).
    if (courseCount === undefined) {
      return generateOrBranch(courses);
    }
    const n = Number.parseInt(courseCount.NUMBER().text, 10);
    if (n === 1) {
      // If there's only 1 course required, and many courses are allowed, then it's
      // same as OR of them all.
      return generateOrBranch(courses);
    }
    return { nOf: [n, courses] };
  };

  visitCourse_items?: ((ctx: Course_itemsContext) => PrereqTree) | undefined = (ctx) => {
    return generateAndBranch(ctx.PROGRAMS_VALUE().map((node) => node.text));
  };

  // Special values

  // @ts-ignore

  // A bare program-type predicate (no THEN) carries no requirement, and the
  // planner has no program-type input, so it is dropped. Program-type *gates*
  // (with a THEN consequence) are handled by visitProgram_types_conditional.
  // @ts-ignore
  visitProgram_types?: ((ctx: Program_typesContext) => PrereqTree) | undefined = () => '';

  // A bare cohort predicate (no THEN, e.g. an AND-ed "COHORT_YEARS MUST_BE_IN
  // S:2017") is an eligibility constraint: the student must be in the cohort to
  // take the module. It gates no requirement, so it has no `then`.
  // @ts-ignore
  visitCohort_years?: ((ctx: Cohort_yearsContext) => PrereqTree) | undefined = (ctx) => {
    const cohort = this.cohortCondition(ctx);
    return cohort === undefined ? '' : { cohort };
  };

  // A cohort that gates a requirement: the requirement only applies to the
  // matching cohorts.
  // @ts-ignore
  visitCohort_conditional?: ((ctx: Cohort_conditionalContext) => PrereqTree) | undefined = (
    ctx,
  ) => {
    const then = ctx.compound()?.accept(this);
    // If the gated requirement simplifies away, there is nothing to require.
    if (then === undefined || then === '') {
      return '';
    }

    const cohort = this.cohortCondition(ctx.cohort_years());
    return cohort === undefined ? '' : { cohort, then };
  };

  // A bare subject-year predicate (no THEN) is an eligibility constraint, the
  // same as a bare cohort. SUBJECT_YEARS only supports IF_IN (see the grammar)
  // and shares COHORT_YEARS' S:/E: year-bound format, so it is surfaced as a
  // cohort-style { cohort } node, mirroring visitCohort_years. No current module
  // uses this bare form, but handling it keeps subject_years from being silently
  // dropped if the data ever does.
  // @ts-ignore
  visitSubject_years?: ((ctx: Subject_yearsContext) => PrereqTree) | undefined = (ctx) => {
    const years = ctx.YEARS().map((node) => node.text);
    return { cohort: { rule: 'IF_IN', years } };
  };

  // A subject-year-gated requirement. SUBJECT_YEARS shares the S:/E: year-bound
  // format of COHORT_YEARS and there is no separate planner input for it, so it
  // is carried as a cohort-style gate evaluated against the matriculation year.
  // @ts-ignore
  visitSubject_years_conditional?:
    | ((ctx: Subject_years_conditionalContext) => PrereqTree)
    | undefined = (ctx) => {
    const then = ctx.compound()?.accept(this);
    // If the gated requirement simplifies away, there is nothing to require.
    if (then === undefined || then === '') {
      return '';
    }
    // subject_years only supports IF_IN (see the grammar).
    const years = ctx
      .subject_years()
      .YEARS()
      .map((node) => node.text);
    return { cohort: { rule: 'IF_IN', years }, then };
  };

  // A program-type-gated requirement: the requirement only applies to students
  // in the matching program type(s). Carried for display; the planner has no
  // program-type input and does not evaluate it.
  // @ts-ignore
  visitProgram_types_conditional?:
    | ((ctx: Program_types_conditionalContext) => PrereqTree)
    | undefined = (ctx) => {
    const then = ctx.compound()?.accept(this);
    // If the gated requirement simplifies away, there is nothing to require.
    if (then === undefined || then === '') {
      return '';
    }
    const programType = this.programTypeGateCondition(ctx.program_types_gate());
    return programType === undefined ? '' : { programType, then };
  };

  cohortCondition(ctx: Cohort_yearsContext): CohortCondition | undefined {
    let rule: CohortRule;
    if (ctx.if_in() !== undefined) {
      rule = 'IF_IN';
    } else if (ctx.if_not_in() !== undefined) {
      rule = 'IF_NOT_IN';
    } else if (ctx.must_be_in() !== undefined) {
      rule = 'MUST_BE_IN';
    } else if (ctx.must_not_be_in() !== undefined) {
      rule = 'MUST_NOT_BE_IN';
    } else {
      this.errors.push(new Error('Cohort years missing a condition'));
      return undefined;
    }
    return { rule, years: ctx.YEARS().map((node) => node.text) };
  }

  programTypeCondition(ctx: Program_typesContext): ProgramTypeCondition | undefined {
    let rule: ProgramTypeRule;
    if (ctx.if_in() !== undefined) {
      rule = 'IF_IN';
    } else if (ctx.must_be_in() !== undefined) {
      rule = 'MUST_BE_IN';
    } else {
      this.errors.push(new Error('Program types missing a condition'));
      return undefined;
    }
    return { rule, types: ctx.PROGRAM_TYPES_VALUE().map((node) => node.text) };
  }

  // A gate may be a disjunction of program types, e.g.
  // `(Undergraduate OR Graduate Coursework)`. Since `IF_IN X OR IF_IN Y` is just
  // `IF_IN X, Y`, collapse the disjunction into a single condition over the
  // union of types. (Real data only uses IF_IN here; the first rule is kept if
  // they ever differ.)
  programTypeGateCondition(ctx: Program_types_gateContext): ProgramTypeCondition | undefined {
    const conditions = collectGateProgramTypes(ctx)
      .map((pt) => this.programTypeCondition(pt))
      .filter((condition): condition is ProgramTypeCondition => condition !== undefined);
    if (conditions.length === 0) {
      this.errors.push(new Error('Program types gate has no conditions'));
      return undefined;
    }
    return {
      rule: conditions[0].rule,
      types: R.uniq(conditions.flatMap((condition) => condition.types)),
    };
  }
}

/**
 * Two program-type conditions describe the same gate when they share a rule and
 * the same set of program types.
 */
function sameProgramType(a: ProgramTypeCondition, b: ProgramTypeCondition): boolean {
  if (a.rule !== b.rule || a.types.length !== b.types.length) {
    return false;
  }
  const others = new Set(b.types);
  return a.types.every((type) => others.has(type));
}

/**
 * Flatten redundant program-type repeats. Because the THEN consequence is
 * greedy, `pt THEN A OR pt THEN B` parses as `pt THEN (A OR (pt THEN B))`.
 * Inside a gate the same gate is always satisfied, so a descendant gate that
 * repeats the enclosing program type is unwrapped to its consequence,
 * recovering the symmetric `pt THEN (A OR B)`. `enclosing` is the nearest
 * ancestor program type, if any.
 */
function normalizeProgramTypes(tree: PrereqTree, enclosing?: ProgramTypeCondition): PrereqTree {
  if (typeof tree !== 'object') {
    return tree;
  }
  if ('programType' in tree) {
    if (enclosing !== undefined && sameProgramType(tree.programType, enclosing)) {
      return normalizeProgramTypes(tree.then, enclosing);
    }
    return {
      programType: tree.programType,
      then: normalizeProgramTypes(tree.then, tree.programType),
    };
  }
  if ('cohort' in tree) {
    return tree.then === undefined
      ? tree
      : { cohort: tree.cohort, then: normalizeProgramTypes(tree.then, enclosing) };
  }
  if ('and' in tree && tree.and !== undefined) {
    return { and: tree.and.map((child) => normalizeProgramTypes(child, enclosing)) };
  }
  if ('or' in tree && tree.or !== undefined) {
    return { or: tree.or.map((child) => normalizeProgramTypes(child, enclosing)) };
  }
  if ('nOf' in tree && tree.nOf !== undefined) {
    const [n, options] = tree.nOf;
    return { nOf: [n, options.map((child) => normalizeProgramTypes(child, enclosing))] };
  }
  return tree;
}

// The lone "Undergraduate Degree" gate is the ubiquitous wrapper almost every
// prereq carries; undergraduates are NUSMods' default audience, so it is assumed
// and carries no information. Any gate naming more — a graduate/CPE type, or
// undergraduate alongside other types — is a real restriction worth keeping.
function isAssumedUndergraduateGate({ types }: ProgramTypeCondition): boolean {
  return types.length === 1 && types[0].toLowerCase() === 'undergraduate degree';
}

/**
 * Drop the single outermost program-type gate only when it is the assumed
 * "Undergraduate Degree THEN ..." wrapper (matching the historical behaviour of
 * ignoring that top-level program type). Any more specific outermost gate — a
 * graduate/CPE-only module, or an "Undergraduate or Graduate" disjunction — is
 * kept and labelled, as it is meaningful signal. Nested or combined (differing)
 * program-type gates are always kept and modelled.
 */
function dropOuterProgramType(tree: PrereqTree): PrereqTree {
  return typeof tree === 'object' &&
    'programType' in tree &&
    isAssumedUndergraduateGate(tree.programType)
    ? tree.then
    : tree;
}

/**
 * Parses the prerequisite string to produce the tokenized form.
 * @see __tests__/parseString.test.js
 */
export default function parseString(prerequisite: string, logger: Logger): PrereqTree | null {
  const chars = CharStreams.fromString(prerequisite);
  const lexer = new NusModsLexer(chars);
  const tokens = new BufferedTokenStream(lexer);
  const parser = new NusModsParser(tokens);
  const errors: Array<string> = [];
  parser.addErrorListener({ syntaxError: (...args) => errors.push(args[4]) });
  const tree = parser.overall();
  if (errors.length > 0) {
    logger.info({ errors: errors, prerequisite }, 'ANTLR encountered parsing errors');
    return null;
  }
  const visitor = new ReqTreeVisitor();
  const result = tree.accept(visitor);
  if (visitor.errors.length > 0) {
    logger.info(
      { errors: visitor.errors, prerequisite },
      'Prereq tree visitor encountered parsing errors',
    );
    return null;
  }
  return dropOuterProgramType(normalizeProgramTypes(result));
}
