import * as React from 'react';
import { shallow } from 'enzyme';

import createHistory from 'test-utils/createHistory';
import { NavtabsComponent } from './Navtabs';

describe(NavtabsComponent, () => {
  test('renders into nav element', () => {
    const navtabs = shallow(
      <NavtabsComponent
        activeSemester={1}
        beta={false}
        promptRefresh={false}
        {...createHistory()}
      />,
    );
    expect(navtabs).toMatchInlineSnapshot(`
      <nav
        className="nav"
      >
        <NavLink
          activeClassName="linkActive"
          className="link"
          to="/timetable/sem-1"
        >
          <Calendar
            color="currentColor"
            size="24"
          />
          <span
            className="title"
          >
            Timetable
          </span>
        </NavLink>
        <NavLink
          activeClassName="linkActive"
          className="link"
          to="/modules"
        >
          <BookOpen
            color="currentColor"
            size="24"
          />
          <span
            className="title"
          >
            Modules
          </span>
        </NavLink>
        <NavLink
          activeClassName="linkActive"
          className="link"
          onFocus={[Function]}
          onMouseOver={[Function]}
          to="/venues"
        >
          <Map
            color="currentColor"
            size="24"
          />
          <span
            className="title"
          >
            Venues
          </span>
        </NavLink>
        <NavLink
          activeClassName="linkActive"
          className="link"
          to="/settings"
        >
          <Settings
            color="currentColor"
            size="24"
          />
          <span
            className="title"
          >
            Settings
          </span>
        </NavLink>
        <NavLink
          activeClassName="linkActive"
          className="link hiddenOnMobile"
          onFocus={[Function]}
          onMouseOver={[Function]}
          to="/contribute"
        >
          <Star
            color="currentColor"
            size="24"
          />
          <span
            className="title"
          >
            Contribute
          </span>
        </NavLink>
        <div
          className="divider"
        />
        <ExternalLink
          className="link hiddenOnMobile"
          href="https://nuswhispers.com"
        >
          <Heart
            color="currentColor"
            size="24"
          />
          <span
            className="title"
          >
            Whispers
          </span>
        </ExternalLink>
      </nav>
    `);
  });
});
