/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-02-19 17:50:15 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@postgres:5432/postgres -t account -s public
 *
 */


export namespace accountFields {
    export type account_id = string;
    export type created_at = Date;
    export type updated_at = Date;
    export type email = string;

}

export interface account {
    account_id: accountFields.account_id;
    created_at: accountFields.created_at;
    updated_at: accountFields.updated_at;
    email: accountFields.email;

}
