export type Contributor = {
  readonly avatar_url: string;
  readonly contributions: number;
  readonly events_url: string;
  readonly followers_url: string;
  readonly following_url: string;
  readonly gists_url: string;
  readonly gravatar_id: string;
  readonly html_url: string;
  readonly id: number;
  readonly login: string;
  readonly organizations_url: string;
  readonly received_events_url: string;
  readonly repos_url: string;
  readonly site_admin: boolean;
  readonly starred_url: string;
  readonly subscriptions_url: string;
  readonly type: string;
  readonly url: string;
};
