FROM node:22-alpine

RUN apk update && \
    apk add --no-cache git python build-base && \
    corepack enable

WORKDIR /home/node/app

ARG DATA_API_BASE_URL
ENV DATA_API_BASE_URL $DATA_API_BASE_URL

ARG GIT_COMMIT_HASH
ENV GIT_COMMIT_HASH $GIT_COMMIT_HASH

CMD pnpm install && (pnpm --filter nusmods start --host 0.0.0.0 & pnpm --filter nusmods start:export --host website)
